eclipse-glsp/glsp-server

- Jenkinsfile
- README.md
Update readme and use pr to test jenkins ci integration
> Resolve #2 Inital jenkins configuration

- Jenkinsfile
- pom.xml
Test-deployment was successfull. Artifacts can be found here
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/glsp/
> #9: Add CI snapshot deployment

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/OperationActionHandler.java
> #21 Make it easier to add operation actions

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/CenterAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/FitToScreenAction.java
- Rename action arguments to match client
- Set missing default values
> Fix CenterAction and FitToScreenAction

- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GEdgeImpl.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/impl/GModelIndexImpl.java
- tests/org.eclipse.glsp.graph.test/resources/graphEdgeBeforeSourceAndTarget.graph
- tests/org.eclipse.glsp.graph.test/src/org/eclipse/glsp/graph/GModelIndexWhenDeserializedFromJsonTest.java
Fixes https://github.com/eclipse-glsp/glsp/issues/50
> Fallback to model search when the GModelIndexImpl is still indexing

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/provider/DefaultToolPaletteItemProvider.java
Fixes https://github.com/eclipse-glsp/glsp/issues/51
> DefaultToolPaletteItemProvider should provide a consistent order

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/handler/CreateOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/OperationActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler/BasicCreateOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/registry/DIOperationHandlerRegistry.java
Fixes eclipse-glsp/glsp/issues/58
> #58 Support for multiple elementTypes per CreateOperationHandler

- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/gson/GModelElementTypeAdapter.java
Resolves eclipse-glsp/glsp/issues/70
> Subtype support for GModelElementTypeAdapter

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/types/NavigationTarget.java
This seems to happen with Theia clients. So we need to account for that
in the server API in NavigationTarget.
https://github.com/eclipse-glsp/glsp/issues/69
> Also support line and columns that have double style (e.g. 1.0)

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/operation/Operation.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/operation/kind/CompoundOperation.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/OperationActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler/CompoundOperationHandler.java
Resolves eclipse-glsp/glsp/issues/76
> Add support for CompoundOperations

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/operation/Operation.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/operation/kind/CompoundOperation.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/OperationActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler/CompoundOperationHandler.java
Resolves eclipse-glsp/glsp/issues/76
> Add support for CompoundOperations (#59)

- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/gson/PropertyBasedTypeAdapter.java
Fixes problem with parsing unknown properties
See also: https://github.com/eclipse/sprotty-server/pull/77/files
Resolves eclipse-glsp/glsp/issues/88
> #88 Apply fix  for PropertyBasedTyeAdapter

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/Action.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/DisposeClientSessionAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/InitializeClientSessionAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/action/DefaultActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/DisposeClientSessionActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/InitializeClientSessionActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DefaultGLSPModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultGLSPServer.java
Also: 
- Use new clientProxy provider instead of deriving the proxy from the client id.
- Fix/Surpress a couple of warnings
- Sort members of MultiBindingDefaults
Follow up for eclipse-glsp/glsp/issues/96
> #96 Introduce InitializeClientSessionAction

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/modelsourcewatcher/FileWatcher.java
- tests/org.eclipse.glsp.server.test/src/org/eclipse/glsp/server/features/modelsourcewatcher/FileWatcherTest.java
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> Fix failing test cases by avoiding debouncing on file watching

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/provider/NodeDocumentationNavigationTargetProvider.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/navigation/JsonOpenerOptions.java
Part of eclipse-glsp/glsp/issues/153
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> #153: Add utility class for JsonOpenerOptions

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SelectAction.java
Fixes https://github.com/eclipse-glsp/glsp/issues/191
> #191: Provide correct kind for SelectAction

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SetViewportAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/Viewport.java
https://github.com/eclipse-glsp/glsp/issues/179
> Adds SetViewportAction

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SaveModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/JsonFileGModelLoader.java
- Extract sub methods for file conversion and model loading to improve extensibility
- Initialize a new empty GGraph if the source file is empty (Fixes eclipse-glsp/glsp/issues/193)
- Use 'ClientOptions.getSourceUriAsFile()' in 'SaveModelActionHandler' to properly handle file uris with 'file://' prefix (Fixes  eclipse-glsp/glsp/issues/200)
> #193 #200 Update model loading  & saving

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/WorkflowDiagramConfiguration.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateAutomatedTaskHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateForkNodeHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateForkOrJoinNodeHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateJoinNodeHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateManualTaskHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateTaskHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateWeightedEdgeHandler.java
* Add css classes on creation to tasks, weighted edge, fork node, join
node
* Make fork and join nodes resizable by providing initial size and
adapting hints
Signed-off-by: Lucas Koehler <lkoehler@eclipsesource.com>
> #220 Rework workflow-example

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/WorkflowDiagramConfiguration.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/diagram/DiagramConfiguration.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/diagram/RequestTypeHintsActionHandler.java
Part of eclipse-glsp/glsp/issues/151
> #151 Cleanup incomplee Refactoring of `ShapeTypeHint`

- examples/org.eclipse.glsp.example.workflow/pom.xml
- plugins/org.eclipse.glsp.graph/pom.xml
- plugins/org.eclipse.glsp.layout/pom.xml
- plugins/org.eclipse.glsp.server.websocket/pom.xml
- plugins/org.eclipse.glsp.server/pom.xml
- pom.xml
Part of eclipse-glsp/glsp/issues/246
> #246 Use generic stand-in developer

- .github/workflows/codeql-analysis.yml
Setup the "CodeQL Analysis" toolcahin that is offered directly by Github to use Actions for automated security analysis.
Part of eclipse-glsp/glsp/issues/237
> #237 Setup automated code scanning alerts

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/WorkflowPopupFactory.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/builder/AbstractGHtmlRootBuilder.java
Use the fluent GModelBuilder API for creating new popup models.
Close eclipse-glsp/glsp/issues/484
> #484 Update WorkflowPopupFactory

- CHANGELOG.md
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/GModelChangeNotifier.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/GModelIndex.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/GModelListener.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/GraphExtension.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/impl/GModelIndexImpl.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/ActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/ActionHandlerRegistry.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/ActionRegistry.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/disposable/IDisposable.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/commandpalette/CommandPaletteActionProvider.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/contextactions/ContextActionsProvider.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/contextactions/ContextActionsProviderRegistry.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/contextmenu/ContextMenuItemProvider.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/directediting/ContextEditValidator.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/directediting/ContextEditValidatorRegistry.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/directediting/LabelEditValidator.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/navigation/NavigationTargetProvider.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/navigation/NavigationTargetProviderRegistry.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/navigation/NavigationTargetResolver.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/popup/PopupModelFactory.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/toolpalette/ToolPaletteItemProvider.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/validation/ModelValidator.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/layout/LayoutEngine.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/model/GModelState.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/CreateOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/OperationHandlerRegistry.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/session/ClientSession.java
Improve API documentation for service interfaces
Co-authored-by: Tobias Ortmayr <tortmayr@eclipsesource.com>
Fixes https://github.com/eclipse-glsp/glsp/issues/487
Contributed on behalf of STMicroelectronics
> #487 Improve GLSP Server API documentation 

- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/GModelIndex.java
Contributed on behalf of STMicroelectronics
> #487 Fix Javadoc parameter

- examples/org.eclipse.glsp.example.workflow/pom.xml
- plugins/org.eclipse.glsp.graph/pom.xml
Fixed https://github.com/eclipse-glsp/glsp/issues/503
> #503: Add 'model' directory to generated maven artifacts

- plugins/org.eclipse.glsp.server/META-INF/MANIFEST.MF
- releng/org.eclipse.glsp.feature/feature.xml
- targetplatforms/r2021-03.target
- targetplatforms/r2021-03.tpd
Fixes eclipse-glsp/glsp/issues/623
> Remove dependency to Apache Commons IO (org.apache.commons.io)

- releng/org.eclipse.glsp.repository/category.xml
- Add newly introduced org.eclipse.server.emf plugin to p2 deployment
Part of https://github.com/eclipse-glsp/glsp/issues/622
> #622 Add new plugin to p2 deployment

- plugins/org.eclipse.glsp.server.emf/META-INF/MANIFEST.MF
Follow-up of https://github.com/eclipse-glsp/glsp/issues/622
> #622 Export missing package org.eclipse.glsp.server.emf.idgen

- CHANGELOG.md
cf. https://github.com/eclipse-glsp/glsp-server/pull/175
> #694 Update CHANGELOG

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/protocol/DefaultGLSPServer.java
Increment protocol version to 1.0.0.
Part of https://github.com/eclipse-glsp/glsp/issues/706
Signed-off-by: Olaf Lessenich <olessenich@eclipsesource.com>
> GH-706 Update protocol version

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/toolpalette/PaletteItem.java
> added a new constructor method providing a custom sort string

- plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/EMFGModelFactory.java
Fixes https://github.com/eclipse-glsp/glsp/issues/905
> Maintain the revision of graph models in `EMFGModelFactory`

- releng/org.eclipse.glsp.repository/category.xml
- targetplatforms/maven-dependencies.tpd
- targetplatforms/r2021-09_minimum-baseline.target
- targetplatforms/r2022-12.target
Required for Jetty 10
Fixes https://github.com/eclipse-glsp/glsp/issues/928
> Adds Ares Spifly to target & update site

- plugins/org.eclipse.glsp.graph/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.layout/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server/META-INF/MANIFEST.MF
Closes https://github.com/eclipse-glsp/glsp/issues/1046
> Adding max version requirements for guava to prevent version conflicts

- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/util/GConstants.java
Fixes https://github.com/eclipse-glsp/glsp/issues/1074
See also https://github.com/eclipse-glsp/glsp/issues/444
> Remove constant for deprecated stack layout

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateWorkflowNodeOperationHandler.java
- plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/EMFCreateOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/GhostElement.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/TriggerNodeCreationAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/gmodel/GModelCreateNodeOperationHandler.java
Relates to https://github.com/eclipse-glsp/glsp/issues/1159
> Add ghost elements to tool palette items through trigger actions

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/WorkflowDiagramConfiguration.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateDecisionNodeHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateMergeNodeHandler.java
- plugins/org.eclipse.glsp.graph/model/glsp-graph.ecore
- plugins/org.eclipse.glsp.graph/model/glsp-graph.genmodel
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GIssue.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GResizable.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GShapeElement.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GraphFactory.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GraphPackage.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GButtonImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GCompartmentImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GIssueImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GIssueMarkerImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GLabelImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GNodeImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GPortImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GResizableImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GraphFactoryImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GraphPackageImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/util/GraphAdapterFactory.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/util/GraphSwitch.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/GResizeLocation.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/builder/GShapeElementBuilder.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/builder/impl/GIssueBuilder.java
- Use string for GResizeLocation
- Fix issue with issue severity not being of type string
> Add Resizable with 'resizeLocations' to shape elements

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/Operation.java
Fixes eclipse-glsp/glsp/issues/1505
> GLSP-1505: Add missing discriminator to operations

- plugins/org.eclipse.glsp.layout/src/org/eclipse/glsp/layout/ElkLayoutEngine.java
Add null check for parent position to `getOffset` computation.
Fixes eclipse-glsp/glsp/issues/1510
> GH-1510: Add null check to ElkLayoutEngine

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/layout/WorkflowLayoutEngine.java
- plugins/org.eclipse.glsp.layout/src/org/eclipse/glsp/layout/ElkLayoutEngine.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/ModelSubmissionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/layout/LayoutEngine.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/LayoutOperation.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/LayoutOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/types/Viewport.java
Relates to https://github.com/eclipse-glsp/glsp/issues/1561
> Extends LayoutOperation with more data and add to layout as parameter

- examples/org.eclipse.glsp.example.workflow/pom.xml
- plugins/org.eclipse.glsp.graph/pom.xml
- plugins/org.eclipse.glsp.layout/pom.xml
- plugins/org.eclipse.glsp.server.emf/pom.xml
- plugins/org.eclipse.glsp.server.websocket/pom.xml
- plugins/org.eclipse.glsp.server/pom.xml
Add name attribute to all pom files to align with the requirements for publishing to maven central
> Fix m2 build

- CHANGELOG.md
- examples/org.eclipse.glsp.example.workflow/META-INF/MANIFEST.MF
- examples/org.eclipse.glsp.example.workflow/pom.xml
- plugins/org.eclipse.glsp.graph/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.graph/pom.xml
- plugins/org.eclipse.glsp.layout/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.layout/pom.xml
- plugins/org.eclipse.glsp.server.emf/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server.emf/pom.xml
- plugins/org.eclipse.glsp.server.websocket/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server.websocket/pom.xml
- plugins/org.eclipse.glsp.server/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server/pom.xml
- pom.xml
- releng/org.eclipse.glsp.feature/feature.xml
- releng/org.eclipse.glsp.feature/pom.xml
- releng/org.eclipse.glsp.repository/pom.xml
- releng/pom.xml
- tests/org.eclipse.glsp.graph.test/pom.xml
- tests/org.eclipse.glsp.server.test/pom.xml
- tests/pom.xml
Switch to nightly 2.6.0-next versions
Note: This pull request was created automatically. After merging, the automated publishing process will be started.
> Switch to nightly 2.6.0-next versions
