eclipse-glsp/glsp-server

- org.eclipse.glsp.api/src/main/java/org/eclipse/glsp/api/utils/LayoutUtil.java
Migrated from https://github.com/eclipsesource/graphical-lsp/pull/393/
> Guard against NPE when copying potentially null size

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/SetContextActions.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/provider/CommandPaletteActionProvider.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/provider/ContextMenuItemProvider.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestContextActionsHandler.java
This ensures that the order is stable and allows the server to control
the order of elements in the command palette on the client.
Resolves #19
> #19 Use lists instead of sets for command palette and menu items

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/Action.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/ActionProcessor.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/SetDirtyStateAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/handler/ActionHandler.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/handler/ServerCommandHandler.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/model/ModelState.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/AbstractActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/CollapseExpandActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/ComputedBoundsActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/DIActionProcessor.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/ExecuteServerCommandActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/LayoutActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/ModelSubmissionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/OpenActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/OperationActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestContextActionsHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestMarkersHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestOperationsActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestPopupModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestTypeHintsActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/SaveModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/SelectActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/UndoRedoActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/ValidateLabelEditActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/model/ModelStateImpl.java
To conveniently let the server handle the dirty state of the editor, I had to also allow the server to send multiple actions as a response to a single action from the client. This is something that may most likely be useful anyway (e.g. to allow the server to center an element after creation, etc.).
Resolves #6
> Let server handle the dirty state

- plugins/org.eclipse.glsp.api/.classpath
- plugins/org.eclipse.glsp.api/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.graph/.classpath
- plugins/org.eclipse.glsp.graph/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.layout/.classpath
- plugins/org.eclipse.glsp.layout/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server.websocket/.classpath
- plugins/org.eclipse.glsp.server.websocket/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server/.classpath
- plugins/org.eclipse.glsp.server/META-INF/MANIFEST.MF
This avoids Eclipse issues with Java10.  This also aligns the plugin configuration and the maven configuration (which uses Java 1.8 anyways)
> Ensure that JavaSE-1.8 is used instead of 10

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestMarkersHandler.java
* RequestMarkersHandler should also deal with lists containing the empty
element like it does with undefined and empty lists
Fix needed for
https://github.com/eclipse-glsp/glsp-examples/pull/33
> Support popups for validation markers (eclipse-glsp/glsp-client#31)

- plugins/org.eclipse.glsp.server.websocket/src/org/eclipse/glsp/server/websocket/GLSPServerEndpoint.java
The increased buffersize allows messages with a length up to 8MB which should be more than enough for most usescases
> Increased buffer size of websocket endpoints

- plugins/org.eclipse.glsp.api/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.api/pom.xml
- plugins/org.eclipse.glsp.graph/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.graph/pom.xml
- plugins/org.eclipse.glsp.layout/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.layout/pom.xml
- plugins/org.eclipse.glsp.server.websocket/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server.websocket/pom.xml
- plugins/org.eclipse.glsp.server/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server/pom.xml
- pom.xml
- releng/org.eclipse.glsp.codestyle/pom.xml
- releng/org.eclipse.glsp.feature/feature.xml
- releng/org.eclipse.glsp.feature/pom.xml
- releng/org.eclipse.glsp.repository/category.xml
- releng/org.eclipse.glsp.repository/pom.xml
- releng/pom.xml
Set version to 0.8.0 snapshot to align with glsp client packages.
> Align snapshot version numbers

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/BasicActionHandler.java
- targetplatforms/r2019-12.target
- targetplatforms/r2019-12.tpd
The deriveActionType() method was not in the constructor. This is necessary to enable abstract subclasses. (similar to how it's done for `BasicOperationHandler` & `BasicCreateOperationHandler`)
> Fix BasicActionHandler constructor

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/Action.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/GLSPServerStatusAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/ServerMessageAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/types/Severity.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/utils/ServerMessageUtil.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/utils/ServerStatusUtil.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultGLSPServer.java
- Provide new ServerMessageAction to handle messages
- Remove 'details' from ServerStatusAction as not displayed in widget
- Fixes eclipse-glsp/glsp/issues/48
Please note this change belongs to this group:
- https://github.com/eclipse-glsp/glsp-examples/pull/40
- https://github.com/eclipse-glsp/glsp-client/pull/46
- https://github.com/eclipse-glsp/glsp/pull/49
- https://github.com/eclipse-glsp/glsp-theia-integration/pull/27
> Add custom action for sending messages from the server to the client

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/Action.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/RequestNavigationTargetsAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/ResolveNavigationTargetAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/SetNavigationTargetsAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/SetResolvedNavigationTargetAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/di/GLSPModule.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/model/NavigationTargetResolver.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/provider/NavigationTargetProvider.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/registry/NavigationTargetProviderRegistry.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/types/NavigationTarget.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/types/NavigationTargetResolution.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestNavigationTargetsActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/ResolveNavigationTargetActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DefaultGLSPModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/registry/DINavigationTargetProviderRegistry.java
This change adds the mechanism for allowing to register `NavigationTargetProvider` to define domain-specific navigations (such as definition, implementation, ...) to diagram-internal elements or diagram-external resources, as well as a `NavigationTargetResolver` for looking up element IDs based on any arguments (e.g. queries).
https://github.com/eclipse-glsp/glsp/issues/69
> Add navigation support and navigation target resolution

- plugins/org.eclipse.glsp.api/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.api/pom.xml
- plugins/org.eclipse.glsp.server.websocket/pom.xml
- plugins/org.eclipse.glsp.server/META-INF/MANIFEST.MF
- pom.xml
- targetplatforms/r2020-06.target
- targetplatforms/r2020-06.tpd
Update to LSP4J 0.9.0 and also update targetplatform to 2020-06 release.
Resolves https://github.com/eclipse-glsp/glsp/issues/75
> #75 Update to LSP4J 0.9.0

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/launch/DefaultGLSPServerLauncher.java
Also improve the log output for the DefaultGlspServerLaucher class.
Resolves eclipse-glsp/glsp/issues/82
> #82 Properly dispose sockets after client connection close

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler/CreateNodeOperationHandler.java
The default implementation just returns the location provided by the operation. Subclasses can overwrite this behavior. (e.g. for grind snapping).
Part of eclipse-glsp/glsp/issues/42
> #42 Add customizable location retrieval to CreateNodeOperationHandler

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/Action.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/SetEditModeAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/di/GLSPModule.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/model/GraphicalModelState.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/model/ModelState.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/utils/ClientOptions.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/OperationActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/RequestModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/SetEditModeActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DefaultGLSPModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/model/JsonFileModelFactory.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/model/ModelStateImpl.java
- Add Readonly support to ModelState and disable operation execution when in readonly mode.
- Introduce SetEditMode action
- Refactor ModelState/GraphicalModelState
- Rename FilebaseModelfactory to JsonFileModelFactory and remove default binding
- Improve parsing methods for ClientOptions (proper handling of null args)
part of eclipse-glsp/glsp/issues/87
> #87 Add readonly support for GLSP diagrams

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/model/ModelState.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/SetEditModeActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/model/ModelStateImpl.java
Store `editMode` string literal in `ModelState` instead of just the readonly boolean flag.
Part of eclipse-glsp/glsp/issues/87
> #87 Make editMode retrievable via ModelState

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/ActionDispatcher.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/di/GLSPModule.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/model/ModelState.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/action/DefaultActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/ClientActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DefaultGLSPModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultGLSPServer.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler/CutOperationHandler.java
- Remove send() method: ActionProcessor.send() should only be called 
by the 'ClientActionHandler'. ActionHandlers that previously called the send()
method directly can now use process() instead.
- Rename `ActionProcessor` to `ActionDispatcher` (align with client side)
part of https://github.com/eclipse-glsp/glsp/issues/21
> #21 Refactor ActionProcessor

- plugins/org.eclipse.glsp.server.websocket/src/org/eclipse/glsp/server/websocket/WebsocketServerLauncher.java
- plugins/org.eclipse.glsp.server/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server/pom.xml
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/launch/CLIParser.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/launch/DefaultCLIParser.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/launch/DefaultGLSPServerLauncher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/launch/GLSPServerLauncher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/LaunchUtil.java
- targetplatforms/r2020-06.target
- targetplatforms/r2020-06.tpd
- Cleanup GLSPServerLauncher (refactor methods & add support to inject additional modules)
- Add a CLIParser helper class and configure default options for configuring
- - Server port
- - consoleLog flag
- - logging directory
- - logLevel
- - help
Fixes eclipse-glsp/glsp/issues/95
> #95 Cleanup GLSPServerLauncher & add CLI parsing

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/LaunchUtil.java
Refactor getAppenders() to avoid usage of Enumeration.asIterator() which is not supported by Java 1.8
Follow-up for:  eclipse-glsp/glsp/issues/95
> Ensure Java 1.8 compatibility in LaunchUtil

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operationhandler/DeleteOperationHandler.java
Log a warning instead of throwing an exception if no elementIds are specified for an DeleteElementAction.
Throwing an exception here will break the command stack. In addition, it's not necessary because technically an empty DeleteElementOperation is still valid (and simply does not affect the model at all)
Fixes eclipse-glsp/glsp/issues/101
> #101 Ensure proper handling of empty DeleteElementOperation

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/ActionDispatcher.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/protocol/GLSPServer.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/action/DefaultActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/GLSPModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultClientSessionManager.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultGLSPServer.java
- Refactor the ActionDispatcher to use an actions queue. Update the API to return CompletableFutures, as the method is now asynchronous.
- Expose the GLSPClient through the injector (Delegating to the GLSPServer)
- Fix some concurrent modification exceptions in DefaultClientSessionManager
fixes eclipse-glsp/glsp/issues/97
> #97 ActionDispatcher should process all messages in the same thread

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/protocol/ClientSessionManager.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/DisposeClientSessionActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultClientSessionManager.java
- Remove the clientId to GLSPClient mapping in ClientSessionManager
fixes eclipse-glsp/glsp/issues/109
Signed-off-by: Camille Letavernier <cletavernier@eclipsesource.com>
> #109 Remove the UUID requirement / ApplicationID

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultClientSessionManager.java
The previous change introduced a ConcurrentModificationException when a client session is disconnected; this PR fixes the regression
> #109 Fix concurrent modification exception when a client disconnects

- plugins/org.eclipse.glsp.server/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/action/DefaultActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultGLSPServer.java
Directly use clientProxy in errorHandler instead of  the actionDispatcher (ActionDispatcher only works if server and session were properly initialized).
> Fix errorHandling in GLPSDefaultServer

- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/Action.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/ConfigureServerHandlersAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/action/kind/InitializeClientSessionAction.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/registry/MapRegistry.java
- plugins/org.eclipse.glsp.api/src/org/eclipse/glsp/api/registry/Registry.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actionhandler/InitializeClientSessionActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DefaultGLSPModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/registry/DIOperationHandlerRegistry.java
When receiving an InitializeClientSessionAction, the server now sends a ConfigureServerHandlersAction which contains the list of actionKinds that the server can handle.
The client can use this to dynamically configure server-handled actions, rather than listing them explicitly.
> #123 Centralize configuration in the server

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/WorkflowGLSPServer.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultGLSPServer.java
This way ensures that the server is only considered "initialized" after the options have  been processed and handled.
Fixes eclipse-glsp/glsp/issues/140
> #140 Properly use completable future during server initialization

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/di/MultiBindingDefaults.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/jsonrpc/DefaultGLSPServer.java
Avoid private members in the default implementation for easier customization in  subclasses.
Follow-up for eclipse-glsp/client/issues/140
> #140 Improve extendibility of DefaultGLSPServer

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/action/DefaultActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/FutureUtil.java
- Aggregate the CompletableFutures from ActionDispatcher#dispatchAll into a single CompletableFuture
- Report this as the result of the Action
Several cases are then possible:
- If an action doesn't have any side-effect ("responses"), the behavior is the same as before
- If an action has a single side-effect, use its result as the action's result
- If an action has multiple side-effects, wait until all of them are complete, then aggregate the exceptions (If any) to complete exceptionally (Otherwise, simply complete the future).
To test this, simply throw exceptions in e.g. ClientActionHandler.send() (As side-effects are typically reply-actions sent to the Client). Without this patch, these actions are not logged/reported. With the patch, the first exception is reported (Other exceptions …
> #124 [Server - ActionDispatcher] Missing error handling for responses

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/launch/DefaultGLSPServerLauncher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/FutureUtil.java
Extend the `DefaultGLSPServerLauncher` to print a message to the output stream once the startup is completed and the server is ready to accept client requests.
This is needed for usecases where the client launches the server itself, in an embedded process. This way the client process can wait for the startup success message from the server before trying to connect to it.
Also: Fix checkstyle warings in 'FutureUtil'
Part of eclipse-glsp/glsp/issues/35
> #35 Extend server launcher for embedded use case

- plugins/org.eclipse.glsp.server.websocket/src/org/eclipse/glsp/server/websocket/GLSPConfigurator.java
- plugins/org.eclipse.glsp.server.websocket/src/org/eclipse/glsp/server/websocket/WebsocketServerLauncher.java
- Create a new Injector instance for each client connection, as expected by the GLSP Server infra
fixes eclipse-glsp/glsp/issues/149
> 149: [Websocket] Do not reuse the same Injector for each client connection

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/navigation/NavigateToExternalTargetAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/di/MultiBindingDefaults.java
- Introduce dedicated 'NavigateToExternalTarget' action
- Fix issue with wrong field name in 'NavigateToTarget' action
Part of eclipse-glsp/glsp/issues/153
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> #153: Improve external navigation support through dedicated action

- plugins/org.eclipse.glsp.server.websocket/META-INF/MANIFEST.MF
- Multiple bundles may provide javax.servlet packages, which can result in some conflicts at runtime. Using a strict package-import, with the same dependency range as Jetty, seems more reliable.
> #156 Use package-import rather than require-bundle for javax.servlet

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SaveModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SetDirtyStateAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/diagram/DiagramConfiguration.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/ModelSubmissionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/RequestModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/undoredo/UndoRedoActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/OperationActionHandler.java
The `SetDirtyStateAction` now also declares the action/operation which caused the dirty state change. 
Ensure that the `SetDirtyStateAction` is only sent once during a model update
Ensure that layout engine is invoked after bounds have been computed (AutomaticServerLayout case)
Part of https://github.com/eclipse-glsp/glsp/issues/197
Fixes https://github.com/eclipse-glsp/glsp/issues/196
> #197 #196 Improve dirty state handling

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SaveModelAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SaveModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/ClientOptions.java
Also update `SaveModelActionHandler` to process the new property accordingly.
If a fileUri has been passed that is not equal to the sourceURi, the handler will save the current modelstate to the new fileUri but keeps the current dirty state
Part of eclipse-glsp/glsp/issues/208
> #208 Add `fileUri` to `SaveModelAction`

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateEdgeHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateManualTaskHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateTaskHandler.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/DefaultTypes.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/builder/GArgumentableBuilder.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/builder/GModelElementBuilder.java
- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/builder/impl/GArguments.java
- Use some known arguments in the workflow example
Fixes https://github.com/eclipse-glsp/glsp/issues/180
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> #180: Add additional default types and improve arguments handling

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateActivityNodeHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateDecisionNodeHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateTaskHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/RequestModelAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/directediting/SetEditValidationResultAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/navigation/NavigationTargetResolution.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/navigation/SetNavigationTargetsAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/navigation/SetResolvedNavigationTargetAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/CreateEdgeOperation.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/CreateNodeOperation.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/CreateOperation.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/gmodel/CreateNodeOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/types/EditorContext.java
Resolves eclipse-glsp/glsp/issues/233
> #233 Add operation arguments to CreateNodeOperationHandler

- Jenkinsfile
- examples/org.eclipse.glsp.example.workflow/pom.xml
- plugins/org.eclipse.glsp.graph/pom.xml
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GArgumentableImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GCompartmentImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GEdgePlacementImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GGraphImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GLabelImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GNodeImpl.java
- pom.xml
- releng/org.eclipse.glsp.repository/pom.xml
- releng/pom.xml
Jenkinsfile:
- Replace `--batch-mode` with shorthand notation and remove unnecessary `package` argument
- Move testing and codestyle checks into separate stages
- Enable checkstyle reporting & publishing as Github check for m2 build
- Publish Junit report as Github check
- Record maven and java warnings
Maven build
- Update metdata
- Update to tycho 2.3.0
- Define src-gen directory in maven-compiler-plugin instead of using the additional builder-helper-maven-plugin
- Replace deprecated typcho-source-feature-plugin
- Improve fatjar profile to fix build warnings regarding overlapping classes.
Java Code:
- Fix warnings in glsp-graph src-gen classes
Part of eclipse-glsp/glsp/issues/60
Part of eclipse-glsp/glsp/issues/17
> #60 #17 Cleanup/update CI & maven build

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/ChangeContainerOperation.java
The definition of the optional member variable location in ChangeContainerOperation does not match on server and client side.
Please see also client change: https://github.com/eclipse-glsp/glsp-client/pull/127
Fixes https://github.com/eclipse-glsp/glsp/issues/253
> #253 Align operation definitions for ChangeContainerOperation

- README.md
This avoids the installing the build artifacts into the local repository which is actually unnecessary and may also lead to problems.
https://github.com/eclipse-glsp/glsp/issues/259
> Replace `mvn install` with `mvn verify`

- examples/org.eclipse.glsp.example.workflow/pom.xml
- plugins/org.eclipse.glsp.graph/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.layout/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.layout/pom.xml
- plugins/org.eclipse.glsp.server/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server/pom.xml
- pom.xml
- releng/org.eclipse.glsp.feature/feature.xml
- targetplatforms/.project
- targetplatforms/r2021-03.target
- targetplatforms/r2021-03.tpd
- tests/org.eclipse.glsp.graph.test/pom.xml
- tests/org.eclipse.glsp.server.test/pom.xml
Update the dependencies to use the latest Guice version available in Orbit (5.0.1) and update the target platform definition to Eclipse 2021-03 to be in line with the TPD of the eclipse-integration.
This indirectly also enforces updates of jupiter, elk and guava dependencies.
This PR contains a workaround to bypass the guava version restriction for elk maven dependencies that can be removed once ELK 0.8.0 is released (this is tracked in  eclipse-glsp/glsp/issues/#265)
Resolves eclipse-glsp/glsp/issues/260
> #260 Update to Guice 5.0.1

- examples/org.eclipse.glsp.example.workflow/pom.xml
- plugins/org.eclipse.glsp.graph/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.graph/pom.xml
- plugins/org.eclipse.glsp.layout/META-INF/MANIFEST.MF
- pom.xml
- releng/org.eclipse.glsp.feature/feature.xml
- targetplatforms/r2021-03.target
- targetplatforms/r2021-03.tpd
Fixes the following alert: https://github.com/eclipse-glsp/glsp-server/security/dependabot/examples/org.eclipse.glsp.example.workflow/pom.xml/com.google.guava:guava/open
> Bump Guava to version 30.1 to fix security alert

- releng/org.eclipse.glsp.repository/pom.xml
- targetplatforms/pom.xml
Fixes the following security alerts:
https://github.com/eclipse-glsp/glsp-server/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster
https://github.com/eclipse-glsp/glsp-server/security/code-scanning/2?query=ref%3Arefs%2Fheads%2Fmaster
> Update maven build to fix security alert

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/launch/DefaultGLSPServerLauncher.java
- Change visibility of `createClientConnection()` to protected
- Extract creation of gsonConfigurator and messageWrapper into submethods so that  they can be easily overwritten.
Fixes eclipse-glsp/glsp/issues/385
> #385 Improve customizability of DefaultGLSPServerLauncher

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/ActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/actions/DefaultActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/launch/DefaultCLIParser.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/protocol/DefaultGLSPServer.java
Remove dispatch method for action messages from API. Action dispatchers are now client session specific and do not need the full message context anymore. The action object alone is enough.
Part of eclipse-glsp/glsp/issues/422
> #422 Cleanup ActionDispatcher API

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/WorkflowDiagramConfiguration.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/gmodel/ChangeBoundsOperationHandler.java
Update `ChangeBoundsOperationHandler` to update the element size instead of the PREF_WIDTH/HEIGHT layout options if the element is not layoutable (i.e. `layout` property is undefined)
Also: Make task nodes resizable to demonstrate that  eclipse-glsp/glsp/issues/219 has been fixed.
Fixes eclipse-glsp/glsp/issues/441
Close eclipse-glsp/glsp/issues/219
> #441#219 Ensure that `newBounds` of ChangeBoundsAction are properly applied

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/layout/WorkflowLayoutEngine.java
- plugins/org.eclipse.glsp.server.websocket/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server.websocket/pom.xml
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/ActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SelectAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/actions/DefaultActionDispatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/gmodel/CreateNodeOperationHandler.java
- targetplatforms/r2021-03.target
- targetplatforms/r2021-03.tpd
- tests/org.eclipse.glsp.server.test/src/org/eclipse/glsp/server/features/modelsourcewatcher/FileWatcherTest.java
and update `WorkflowLayoutEngine` to dispatch a `CenterAction` after the next model update.
Fixes https://github.com/eclipse-glsp/glsp/issues/448
> #448 Implement dispatching of actions on next model-update

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/JsonFileGModelLoader.java
Fixes https://github.com/eclipse-glsp/glsp/issues/467
> #467: Use graph as default root element instead of plain model root

- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GEdgeImpl.java
Fixes https://github.com/eclipse-glsp/glsp/issues/460
Before:
After:
> #460: Notify source/target feature change on source/target id change

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/handler/CreateCategoryHandler.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/labeledit/WorkflowLabelEditValidator.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/marker/WorkflowModelValidator.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/utils/WorkflowBuilder.java
https://github.com/eclipse-glsp/glsp/issues/492
> Improve styling and simplify workflow example

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/AbstractActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/BasicActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/ResponseAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/util/GenericsUtil.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/AbstractCreateOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/AbstractOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/BasicCreateOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/BasicOperationHandler.java
- tests/org.eclipse.glsp.server.test/pom.xml
- tests/org.eclipse.glsp.server.test/src/org/eclipse/glsp/server/internal/util/GenericsUtilTest.java
- Ensure we start from the most specific class and climb up the type
hierarchy to search for the matching actual type argument
Part of https://github.com/eclipse-glsp/glsp/issues/534
> #534: Provide utility methods to properly match actual type argument

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/operations/gmodel/LayoutOperationHandler.java
Otherwise Guice would through an error if no layout engine is bound by
the module (which is fine however).
Fixes https://github.com/eclipse-glsp/glsp/issues/600
> Ensure that LayoutEngine is only injected into an optional field

- CHANGELOG.md
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/WorkflowDiagramModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SaveModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DiagramModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/GModelJsonDiagramModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/GModelFactory.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/JsonFileGModelStore.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/RequestModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/SourceModelStorage.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/modelsourcewatcher/FileWatcher.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/modelsourcewatcher/SourceModelWatcher.java
With this change, I'd like to consistently use the term source model and
avoid the term model source. This is to avoid the overlap with Sprotty's
concept of ModelSource and its unclear relation to a source model and
GModel.
I suggest to avoid Model Source altogether and instead introduce and
consistently use "source model" to refer to the underlying model that we
read and write. Thus we have in GLSP two types of models:
* Source Model
* Graph Model (GModel)
Thus, I did the following refactorings:
* Rename ModelSourceLoader to SourceModelPersistence
* Add saving to the SourceModelPersistence interface
* Delegate from the SaveModelActionHandler to that implementation
* Rename ModelSourceWatcher into SourceModelWatcher
* Update javadoc and variable names where fit
Fixes …
> Refactorings regarding source model loading and saving

- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/layout/WorkflowLayoutEngine.java
* Remove bendpoints, because they are inconvenient for editing later on
* Set alignmenet of node placement to balanced
> Improve workflow layouter

- CHANGELOG.md
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/model/DefaultGModelState.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/model/ModelState.java
Part of https://github.com/eclipse-glsp/glsp/issues/622
> #622: Remove 'setRoot' from API in favor of 'updateRoot'

- README.md
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/launch/WorkflowCLIParser.java
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/launch/WorkflowServerLauncher.java
- plugins/org.eclipse.glsp.server.websocket/META-INF/MANIFEST.MF
- plugins/org.eclipse.glsp.server.websocket/src/org/eclipse/glsp/server/websocket/WebsocketServerLauncher.java
- Make console log level for websocket jetty server configurable (is Level WARN by default)
- Update README
Resolves https://github.com/eclipse-glsp/glsp/issues/658
> #658 Fix console log level for WebsocketLauncher

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DiagramModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/actions/DefaultActionDispatcher.java
Client session listeners only get notified about the session disposal after the session and its action dispatcher are disposed. As they might perform some cleanup we should ensure that all pending actions are executed before the action dispatcher is disposed and the listeners are notified.
Fixes https://github.com/eclipse-glsp/glsp/issues/635
> #635: Execute all pending actions before disposing action dispatcher

- releng/org.eclipse.glsp.repository/category.xml
Follow-up of https://github.com/eclipse-glsp/glsp/issues/622
- Add `glsp.server.emf.source` to p2 plugin to improve development experience
> #622 Add glsp.server.emf source to p2 plugin

- plugins/org.eclipse.glsp.graph/model/glsp-graph.ecore
- plugins/org.eclipse.glsp.graph/model/glsp-graph.genmodel
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GGraph.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GLayoutable.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GShapeElement.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GraphFactory.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/GraphPackage.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GButtonImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GCompartmentImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GGraphImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GIssueMarkerImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GLabelImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GLayoutableImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GNodeImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GPortImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GraphFactoryImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/impl/GraphPackageImpl.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/util/GraphAdapterFactory.java
- plugins/org.eclipse.glsp.graph/src-gen/org/eclipse/glsp/graph/util/GraphSwitch.java
- Update the Graph model for consistency with the Sprotty API
- GShapeElement is a GLayoutable and can have layoutOptions
refs https://github.com/eclipse-glsp/glsp/issues/694
> #694: Add Layoutable interface

- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/builder/impl/GArguments.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/ComputedBoundsAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/gmodel/GModelChangeRoutingPointsHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/LayoutUtil.java
Part of https://github.com/eclipse-glsp/glsp/issues/738
> #738: Add route data to ComputedBoundsAction

- pom.xml
- targetplatforms/pom.xml
This is needed to build with maven and Java 17.
Related to this, includePackedArtifacts had to be disabled as it seems to cause issues with Java 14 and higher.
Closes https://github.com/eclipse-glsp/glsp/issues/750
Signed-off-by: Olaf Lessenich <olessenich@eclipsesource.com>
> Update tycho maven version: 2.3.0 => 2.7.5

- plugins/org.eclipse.glsp.server.websocket/src/org/eclipse/glsp/server/websocket/WebsocketServerLauncher.java
closes https://github.com/eclipse-glsp/glsp/issues/883
remove listening on stdin, so that the server can be started without access to stdin and rely on process control to stop
> don't wait on stdin in websocket server

- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/util/IdKeeperAdapter.java
This is crucial to make sure that IDs are stable with UUIDIdGenerator within one session.
Fixes https://github.com/eclipse-glsp/glsp/issues/897
> Ensure existing IdKeeperAdapters are found

- CHANGELOG.md
- plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/EMFDiagramModule.java
- plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/EMFModelState.java
- plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/EMFModelStateImpl.java
- plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/notation/EMFNotationDiagramModule.java
- plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/notation/EMFNotationModelState.java
- plugins/org.eclipse.glsp.server.emf/src/org/eclipse/glsp/server/emf/notation/EMFNotationModelStateImpl.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/model/DefaultGModelState.java
- Use interfaces for EMFModelState and EMFNotationModelState
- Use these interfaces for binding and injection
refs https://github.com/eclipse-glsp/glsp/issues/974
> GLSP-974: Use interface-injection for all subclasses of ModelState

- CHANGELOG.md
- examples/org.eclipse.glsp.example.workflow/src/org/eclipse/glsp/example/workflow/marker/WorkflowModelValidator.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/ModelSubmissionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/validation/MarkersReason.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/validation/ModelValidator.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/validation/RequestMarkersAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/validation/RequestMarkersHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/validation/SetMarkersAction.java
https://github.com/eclipse-glsp/glsp/issues/980
For review, please see [the comment on which changes belong together](https://github.com/eclipse-glsp/glsp/issues/980#issuecomment-1516867263).
> Add validation reason and distinguish between live and batch validation

- CHANGELOG.md
- README.md
- examples/org.eclipse.glsp.example.workflow/Start_Workflow_Example_Server.launch
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/LaunchUtil.java
This sets the default port to 0, which will cause the server to automatically assign a port. The port is then printed to the console in the startup message and can be parsed by clients.
Part of eclipse-glsp/glsp#965
> feat: adjust server startup to use autoassigned ports

- Jenkinsfile
- examples/org.eclipse.glsp.example.workflow/pom.xml
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/ClientId.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DiagramType.java
- pom.xml
- Remove direct dependency to javax.inject by switching to google.inject counterparts
Due to the namespace switch from javax->jakarta with Java17 it's otherwise hard to maintain a build that works for both 11 and 17.
- Remove `illegal-access=permit" flag from plugin configuration as it is no longer supported in Java17 
- Update maven-shade plugin config to get rid of warnings 
- Introduce a new orthogonal Java11 compatibility build job that is triggered for every master commit
Fixes https://github.com/eclipse-glsp/glsp/issues/991
> GLSP-991: Switch Jenkins build to Java 17

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/SelectAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/gmodel/GModelCreateNodeOperationHandler.java
- Introduce optional flag that indicates deselection of all elements
- Introduce convenience creation methods for Select action
https://github.com/eclipse-glsp/glsp/issues/979
> GLSP-979: Introduce 'deselectAll' flag for SelectAction

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/EndProgressAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/ServerMessageAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/StartProgressAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/actions/UpdateProgressAction.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DiagramModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/RequestModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/progress/DefaultProgressService.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/progress/ProgressMonitor.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/progress/ProgressService.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/ServerMessageUtil.java
https://github.com/eclipse-glsp/glsp/issues/1019
> Add support for progress reporting

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/RequestModelActionHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/utils/ClientOptionsUtil.java
If Websocket connections reconnect after an interrupt, ensure that the last modelState is restored on RequestModelAction if available
Part of https://github.com/eclipse-glsp/glsp/issues/77
---
Related to: https://github.com/eclipse-glsp/glsp-client/pull/269
https://github.com/eclipse-glsp/glsp-server-node/pull/54
> GLSP-77: Allow WebSocket connections to reconnect after interrupt

- Jenkinsfile
- releng/org.eclipse.glsp.repository/pom.xml
The tycho-ant-run task for creating the composite update site seems to break with Java17. Since this task is just creating the update site the Java version is not really relevant so for now we switch back to 11. Update jenkins file to trigger Java21 compatibility when on master merges.
> GLSP-1127: Fix publish build

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/gmodel/GModelDeleteOperationHandler.java
Fix GModelDeleteOperationHandler by updating the collectDependents method.
- Dont add child elements of elements that should be deleted to the dependent set. They will be deleted indirectly anyways because the parent container is deleted.
- Correctly add incoming/outgoing edges to the dependet set instead of their targets/sources
> Bugfixes for 2.0

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/actions/DefaultActionDispatcher.java
Always execute post update queue even if there is no handler for the UpdateModelAction
> Fixes eclipse-glsp/glsp#1212

- pom.xml
The error was caused by maven that used log4j with the version `3.0.0-beta`. 
The targetplatform uses `2.19.0` - now we are limiting the version of log4j to be in range of `2.19.0` <= x <= `2.23.1` for maven. We probably also should limit the rest of the dependencies.
~Moreover, I was not able to use the build the project with Eclipse IDE and had to change the location of `jetty` within the targetplatform.~ *Fixed by installing PDE M2 Integration* 
Closes https://github.com/eclipse-glsp/glsp/issues/1312
Run the following command in the root folder:
`mvn clean verify -Pm2 -Pfatjar && java -jar ./examples/org.eclipse.glsp.example.workflow/target/org.eclipse.glsp.example.workflow-2.1.0-glsp.jar -p 8081 -w`
The following error should not be thrown anymore:
```
Exception in thread "main" …
```
> Fix log4j version

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/actions/DefaultActionDispatcher.java
- Extract thread creation and initialization out of constructor
- Check that everything works as before.
> Make ActionDispatcher more easily customizable

- CHANGELOG.md
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/di/DiagramModule.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/internal/actions/DefaultActionDispatcher.java
Fixes: https://github.com/eclipse-glsp/glsp/issues/1387
Do not register the DefaultActionDispatcher as ActionHandler, instead create a new inner class JoinActionHandler that handles the JoinAction.
See issue
> GLSP-1387 Do not bind DefaultActionDispatcher as ActionHandler

- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/features/core/model/ModelSubmissionHandler.java
- Introduce asynchronous live validation behavior
- Send status message
https://github.com/eclipse-glsp/glsp/issues/1408
- Any workflow example
- Add breakpoint to the validation so that it takes longer and you can see the message
- See that while breakpoint is active you can perform other operations
> GLSP-1408: Make live validation asynchronous

- plugins/org.eclipse.glsp.graph/src/org/eclipse/glsp/graph/util/GraphUtil.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/gmodel/GModelChangeBoundsOperationHandler.java
- plugins/org.eclipse.glsp.server/src/org/eclipse/glsp/server/gmodel/GModelChangeRoutingPointsHandler.java
- Filter empty change bounds and change routing points operations
- Filter empty compound commands
Relates to eclipse-glsp/glsp#1477
- Move an element without actually snapping to a new position
- Debug server state or observer undo/redo stack is correctly as there are no operations on the command stack
> Avoid executing unnecessary operations
